baseURL = "https://test.waterfall-lodge.org.uk/"
languageCode = "en-gb"
title = "Waterfall Lodge No 4139 Test"

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Test static Hugo rebuild of the Waterfall Lodge WordPress site."
