baseURL = "https://test.waterfall-lodge.org.uk/"
languageCode = "en-gb"
title = "Waterfall Lodge No. 4139"

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Waterfall Lodge No. 4139, Freemasons in Chertsey, Surrey."
